repositories:
  - name: nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  createNamespace: true
  chart: nginx/ingress-nginx
  version: 4.4.2
  values:
    - values/ingress-nginx/values.yaml