repositories:
  - name: nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jenkins
    url: https://charts.jenkins.io
  - name: gitea
    url: https://dl.gitea.com/charts/

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  createNamespace: true
  chart: nginx/ingress-nginx
  version: 4.4.2
  values:
    - values/ingress-nginx/values.yaml
- name: jenkins
  namespace: jenkins
  createNamespace: true
  chart: jenkins/jenkins
  version: 5.0.14
  values:
    - values/jenkins/values.yaml
- name: gitea
  namespace: gitea
  createNamespace: true
  chart: gitea/gitea
  version: 10.1.1
  values:
    - values/gitea/values.yaml